FROM node:20-alpine AS builder
WORKDIR /app
COPY server/package*.json ./
RUN npm ci --omit=dev

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY server/ ./
EXPOSE 8888
CMD ["node", "server.js"]
