sonar.projectKey=ZarbL_projetoindividual
sonar.organization=zarbl

sonar.projectName=mk.js
sonar.projectVersion=1.0

sonar.sources=server,game/src
sonar.tests=server/__tests__
sonar.exclusions=server/node_modules/**,server/coverage/**,server/__tests__/**

sonar.javascript.lcov.reportPaths=server/coverage/lcov.info

sonar.coverage.exclusions=server/server.js
