apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mkjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - until pg_isready -h db -U postgres -d mkjs; do echo "Aguardando DB..."; sleep 2; done
      containers:
        - name: backend
          image: ghcr.io/zarbl/mkjs-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
          readinessProbe:
            httpGet:
              path: /health
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
